### ISSUE TITLE
Owner with no access

### ISSUE THREAD

**Issue by ttacke** [seibert-media/teamvault#115]
- "ben" and I are the owner of a secret
- only "ben" is allowed to access the secret
- so I request for access
- "ben" and I got notifications about the request
- when I click on "Allow access" I've got a 403

Sollutions:
- If you've no permittsion, you should not got notofications
- If you'r the owser, maybe you should have access

PS: Maybe the reason for https://github.com/seibert-media/teamvault/issues/101

**Comment by trehn** [comment]
absoleted by 0c65c95a4268e4bebbd42ea5e1e6f2f1305a0fc0
